export default {
	theme: 'light',
	colorWeak: false,
	navbar: true,
	menu: true,
	hideMenu: false,
	menuCollapse: false,
	footer: false,
	themeColor: '#3491FA',
	menuWidth: 220,
	globalSettings: false,
	device: 'desktop',
	tabBar: true,
	name: 'Wilson Panel',
	title: 'Wilson Panel',
	desc: '开源的饥荒游戏平台，轻松搭建属于您的游戏集群',
	subDesc: '分布式，弹性化，自动化，可迁移，功能强大的游戏面板',
	layout: 'default',
	skin: 'default',
	watermark: '',
	copyright: 'Copyright © 2025 dstgo.cn. All rights reserved.',
	language: 'zh_CN',
	animation: 'gp-slide-down'
};
